name:                Logic
version:             0.1.0.1
synopsis:            Propositional, Modal and Propositional Dynamic Logic.
description:         n/a
maintainer:          Malvin Gattinger <malvin@w4eg.de>
license:             GPL-3
category:            Logic

ghc-options:        -Wall

extra-source-files:
  - README.md
  - LICENSE
  - stack.yaml
  - package.yaml
  - src/Logic/PDL/Parse.y
  - src/Logic/PDL/Lex.x

build-tools:
  - alex
  - happy

library:
  source-dirs:
    - src
  dependencies:
    - ansi-terminal
    - base >= 4.7 && < 5
    - array
    - containers
    - graphviz
    - hspec
    - process
    - QuickCheck
    - random
    - temporary

tests:
  propositional:
    source-dirs:
      - test
    main: propositional.hs
    dependencies:
      - base >= 4.7 && < 5
      - hspec
      - QuickCheck
      - Logic
  basicmodal:
    source-dirs:
      - test
    main: basicmodal.hs
    dependencies:
      - base >= 4.7 && < 5
      - hspec
      - QuickCheck
      - Logic
  pdl:
    source-dirs:
      - test
    main: pdl.hs
    dependencies:
      - base >= 4.7 && < 5
      - hspec
      - QuickCheck
      - Logic
