# thanks to https://github.com/rolandtritsch/haskell-aoc-2020

on: [push]

name: CI

jobs:
  build:
    name: Build and run tests
    runs-on: ubuntu-latest
    steps:
    - name: Cache
      uses: actions/cache@v2
      with:
        key: stack
        path: |
          ~/.stack
          ~/.stack-work
    - uses: actions/checkout@v2
    - name: Compile
      run: stack --system-ghc test --no-run-tests
    - name: "Run tests: propositional"
      run: stack --system-ghc test Logic:test:propositional
    - name: "Run tests: basicmodal"
      run: stack --system-ghc test Logic:test:basicmodal
    - name: "Run tests: pdl"
      run: stack --system-ghc test Logic:test:pdl
    - name: "Run example"
      run: stack --system-ghc exec example
  build-web:
    name: Buld web interface
    runs-on: ubuntu-latest
    steps:
    - name: Cache
      uses: actions/cache@v2
      with:
        key: stack
        path: |
          ~/.stack
          ~/.stack-work
    - uses: actions/checkout@v2
    - name: Compile web interface
      run: stack --system-ghc build Logic:exe:tapdleau
